urlShortner/urlShortner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^admin/', include(admin.site.urls)),
    # if the URL pattern match /admin/ then open up admin panel

]

urlpatterns += [
    url(r'', include('urlShortnerWebsite.urls', namespace='urlShortnerWebsite')),
    # if anything rather then /admin/ then it will look for shortenersite/urls


]

urlShortner/urlShortnerWebsite/urls.py
from django.conf.urls import include, url
from urlShortnerWebsite import views
from urlShortnerWebsite.views import index, redirect_original, shorten_url

app_name="urlShortnerWebsite"


urlpatterns = [
    url(r'^$', index, name='home'),
    # for our home/index page

    url(r'^(?P<short_id>\w{8})$', redirect_original, name='redirectoriginal'),
    # when short URL is requested it redirects to original URL

    url(r'^makeshort/$', shorten_url, name='shortenurl'),
    # this will create a URL's short id and return the short URL
]

urlShortner/urlShortnerWebsite/models.py
from django.db import models

# Create your models here.
class Urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

def __str__(self):
    return self.httpurl

urlShortner/urlShortnerWebsite/views.py
from django.shortcuts import render_to_response, get_object_or_404
import random, string, json
from urlShortnerWebsite.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.views.decorators import csrf
from django.shortcuts import render

def index(request):
    c = {}
    return render(request, 'urlShortnerWebsite/index.html', c)

def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id) # get object, if not found return 404 error
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.httpurl)

def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        #for i in savedUrls.httpurl
        # ##############중복되는 부분 거르는 것을 잘 모르겠음...~~ ㅠㅠ
        #     if i == url:
        #         response_data = {}
        #         response_data['url'] = settings.SITE_URL + "/" + savedUrls.short_id
        #         return HttpResponse(json.dumps(response_data), content_type="application/json")
        #         #######################################
            #else:
                short_id = get_short_code()
                b = Urls(httpurl=url, short_id=short_id)
                b.save()
                response_data = {}
                response_data['url'] = settings.SITE_URL + "/" + short_id
                return HttpResponse(json.dumps(response_data), content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}),
             content_type="application/json")

def get_short_code():
    length = 8
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # 랜덤으로 url 생성
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

urlShortner/urlShortnerWebsite/templates/urlShortnerWebsite/base.html
<!DOCTYPE html>
<html>
    <head>
         <title>{% block title %}Welcome to mysite{% endblock %}</title>
         {% load staticfiles %}
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
         <link rel="stylesheet" type="text/css" href="{% static 'urlShortnerWebsite/css/main.css' %}" />
         <link rel="stylesheet" type="text/css" href="{% static 'urlShortnerWebsite/css/nice-select.css' %}" />
         <link rel="stylesheet" type="text/css" href="{% static 'urlShortnerWebsite/css/custom.css' %}" />
         <link rel="stylesheet" type="text/css" href="{% static 'urlShortnerWebsite/css/owl.carousel.css' %}" />
         <link rel="stylesheet" type="text/css" href="{% static 'urlShortnerWebsite/css/pgwslider.min.css' %}" />
         <link rel="stylesheet" type="text/css" href="{% static 'urlShortnerWebsite/css/linearicons.css' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/vendor/bootstrap.min.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/vendor/jquery-2.2.4.min.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/jquery.ajaxchimp.min.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/jquery.magnific-popup.min.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/jquery.nice-select.min.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/main.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/owl.carousel.js' %}" />
         <link rel="stylesheet" type="text/javascript" href="{% static 'urlShortnerWebsite/js/pgwslider.min.js' %}" />
         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
         <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <script type="text/javascript">
     $(function() {
     $('#submitButton').click(function() {
     $.ajax({
     type: "POST",
     url: "/makeshort/",
     data: {
     'url' : $('#url').val(),
     'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
     },
     success: returnSuccess,
     dataType: 'json'
     });
     });
    });

    function returnSuccess(data, textStatus, jqXHR) {
     if(data.url) {
     $('#url-result').text(data.url);
     $('#url').val("");
     } else {
     $('#url-result').text("Do not submit blank.");
     }

    }
    </script>
    <body>
        <div class="dup-body-wrap">
        <section class="banner-area relative">
            <header>
             <h1><a href="{% url 'urlShortnerWebsite:home' %}">Nuri's URL Shortner</a></h1>
            </header>


        <body class="dup-body">

                            {% block content %}

                            {% endblock %}

                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-4">
                        <img src="img/banner.png" alt="" class="img-fluid">
                    </div>
                </div>
            </div>
        </section>
        </div>

        <script src="js/vendor/jquery-2.2.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="js/vendor/bootstrap.min.js"></script>
        <script src="js/jquery.ajaxchimp.min.js"></script>
        <script src="js/owl.carousel.min.js"></script>
        <script src="js/jquery.nice-select.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/main.js"></script>
    </body>
    </body>
</html>

urlShortner/urlShortnerWebsite/templates/urlShortnerWebsite/index.html
{% extends "urlShortnerWebsite/base.html" %}

{% block title %}Nuri's URL Shortner{% endblock %}

{% block content %}

 <div class="panel-body">
     <div class="col-sm-9">
     <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.facebook.com" />
     </div>
     <div class="col-sm-3">
     {% csrf_token %}
     <button id="submitButton" class="primary-btn">Change!<span class="lnr lnr-arrow-right"></span></button></p>
      </div>
 </div>
 <div class="panel-footer"><span id="url-result">Write the URL you want to make shorten, and click the button!</span></div>
</div>
{% endblock %}